version: '3.1'

services:

    db:
        image: mariadb
        container_name: user_db
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_PASSWORD: nimda
            MYSQL_USER: admin
            MYSQL_DATABASE: users
        volumes:
            - "./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
